# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agec < Formula
  desc ""
  homepage ""
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aca/agec/releases/download/v0.2.3/agec_0.2.3_darwin_amd64"
      sha256 "f23006c688609c625886f939b705006293087de036c623e2086bee92d04477af"

      def install
        bin.install "agec"
        generate_completions_from_executable(bin/"agec", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aca/agec/releases/download/v0.2.3/agec_0.2.3_darwin_arm64"
      sha256 "6acea6934af14d80acc7e8bbba2a7c9fd80f5559445cabd85f8a3ccfd9c7d4ae"

      def install
        bin.install "agec"
        generate_completions_from_executable(bin/"agec", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aca/agec/releases/download/v0.2.3/agec_0.2.3_linux_amd64"
      sha256 "39ad4ff29f884b64b4ee7c4c18f21bf489853a28e6b5887ea792625a20066d19"

      def install
        bin.install "agec"
        generate_completions_from_executable(bin/"agec", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aca/agec/releases/download/v0.2.3/agec_0.2.3_linux_arm64"
      sha256 "e934f38cd18c462ecb9c4690530ecf59cd532e1ec69928a03684a7e5d2477e31"

      def install
        bin.install "agec"
        generate_completions_from_executable(bin/"agec", "completion")
      end
    end
  end
end
