# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agec < Formula
  desc ""
  homepage ""
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aca/agec/releases/download/v0.2.4/agec_0.2.4_darwin_amd64"
      sha256 "f90a4deda51238c055d42e42ef21b8e5bad2b0f5aed88fa2eb494df352b4312d"

      def install
        bin.install "agec_0.2.4_darwin_amd64" => "agec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aca/agec/releases/download/v0.2.4/agec_0.2.4_darwin_arm64"
      sha256 "86cd867a9814ff54a81f0811137319fafd0bd0460c1bd6b005826b5a1bf82193"

      def install
        bin.install "agec_0.2.4_darwin_arm64" => "agec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aca/agec/releases/download/v0.2.4/agec_0.2.4_linux_arm64"
      sha256 "83ed582978c4b5fff297fba511bbf86c6d35a28b265978544739f8ef68a94111"

      def install
        bin.install "agec_0.2.4_linux_arm64" => "agec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aca/agec/releases/download/v0.2.4/agec_0.2.4_linux_amd64"
      sha256 "c5730ca9201323c6609052213dfb2497184b3e0b1270c729df6ab1e47a14bfd9"

      def install
        bin.install "agec_0.2.4_linux_amd64" => "agec"
      end
    end
  end
end
