# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testrelease < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aca/testrelease/releases/download/v0.1.0/testrelease_0.1.0_darwin_arm64"
      sha256 "a17cea9c10b3b6a31bb50a3dc0bd284ba844240f37212b46831680284bd12c20"

      def install
        bin.install "testrelease"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aca/testrelease/releases/download/v0.1.0/testrelease_0.1.0_darwin_amd64"
      sha256 "f3e58495dfdc95dfc8129609f7290a6120f53b6e82c26e9f596d85eed6db55d3"

      def install
        bin.install "testrelease"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aca/testrelease/releases/download/v0.1.0/testrelease_0.1.0_linux_arm64"
      sha256 "dc10488924f915d6643301236ce0a4d1d61e9646cfcce38b8ff4891321531e19"

      def install
        bin.install "testrelease"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aca/testrelease/releases/download/v0.1.0/testrelease_0.1.0_linux_amd64"
      sha256 "ea08c8a474add38c98aa84948dc5471076f2a9c650fe277e687051ba0b1a0eca"

      def install
        bin.install "testrelease"
      end
    end
  end
end
